project:
  type: website
  output-dir: docs
  execute-dir: project

website:
  title: "StatProg2 Group Project"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: pages/proposal.qmd
        text: Proposal
      - href: pages/group_reflection.qmd
        text: Group Reflection


format:
  html:
    theme: [cosmo, styles.scss]
    toc: true
    code-fold: true
